// COPYRIGHT Dassault Systemes 2024
//===================================================================
//
// Function1Cmd.h
// The state chart based command: Function1Cmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
// CAA2 Wizard Generation Report
//   STATECOMMAND
// End CAA2 Wizard Generation Report
//
//  Dec 2024  Creation: Code generated by the CAA wizard  root
//===================================================================
#ifndef Function1Cmd_H
#define Function1Cmd_H

#include "CAAFunction.h"
#include <CATStateCommand.h>

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class Function1Cmd: public CATStateCommand
{
    // Allows customization/internationalization of command's messages
    // ---------------------------------------------------------------
    DeclareResource(Function1Cmd, CATStateCommand);

public:
    Function1Cmd();
    virtual ~Function1Cmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
    virtual void BuildGraph();

    virtual CATBoolean ActionOne(void *data);

private:
    CATPathElementAgent *_daPathElement;
    CATSoftwareConfiguration *pSoftConfig;
    CATTopData TopData;
};

//----------------------------------------------------------------------

#endif
