// COPYRIGHT Dassault Systemes 2025
//===================================================================
//
// CAAPluginWks.cpp
// Provide implementation to interface
//    CATIPRDWorkshopAddin
//    CATIPrtWksAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Jan 2025  Creation: Code generated by the CAA wizard  root
//===================================================================
#include "CAAPluginWks.h"

#include <CATCommandHeader.h>
#include <CATCreateWorkshop.h>
MacDeclareHeader(CAAPluginHdr);
CATImplementClass(CAAPluginWks, Implementation, CATBaseUnknown, CATnull);

//-----------------------------------------------------------------------------
// CAAPluginWks : constructor
//-----------------------------------------------------------------------------
CAAPluginWks::CAAPluginWks()
    : CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// CAAPluginWks : destructor
//-----------------------------------------------------------------------------
CAAPluginWks::~CAAPluginWks()
{
}

// Link the implementation to its interface
// ---------------------------------------

void CAAPluginWks::CreateCommands()
{
    new CAAPluginHdr("CAAPluginCmd1", "CAAPluginCmd", "CAAPluginCmd1", (void *)0);
}

CATCmdContainer *CAAPluginWks::CreateToolbars()
{
    NewAccess(CATCmdContainer, pCAAPluginTlb, CAAPluginWks);

    NewAccess(CATCmdStarter, pCAAPluginCmd1, CAAPluginStr1);
    SetAccessCommand(pCAAPluginCmd1, "CAAPluginCmd1");
    SetAccessChild(pCAAPluginTlb, pCAAPluginCmd1);

    AddToolbarView(pCAAPluginTlb, 1, Left);
    return pCAAPluginTlb;
}

// TIE or TIEchain definitions
#include "TIE_CATIPRDWorkshopAddin.h"
TIE_CATIPRDWorkshopAddin(CAAPluginWks);
#include "TIE_CATIPrtWksAddin.h"
TIE_CATIPrtWksAddin(CAAPluginWks);

// Methods implementation
