// COPYRIGHT Dassault Systemes 2025
//===================================================================
//
// CAAPluginCmd1.h
// The state chart based command: CAAPluginCmd1
//
//===================================================================
//
// Usage notes:
//
//===================================================================
// CAA2 Wizard Generation Report
//   STATECOMMAND
// End CAA2 Wizard Generation Report
//
//  Jan 2025  Creation: Code generated by the CAA wizard  root
//===================================================================
#ifndef CAAPluginCmd1_H
#define CAAPluginCmd1_H

#include "CAAPlugin.h"
#include "CATStateCommand.h"

#include "CATPathElementAgent.h"
#include "CATSoftwareConfiguration.h"
#include "CATTopData.h"

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class CAAPluginCmd1: public CATStateCommand
{
    // Allows customization/internationalization of command's messages
    // ---------------------------------------------------------------
    DeclareResource(CAAPluginCmd1, CATStateCommand)

        public:

        CAAPluginCmd1();
    virtual ~CAAPluginCmd1();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
    virtual void BuildGraph();

    /**
     * Action associated to state transitions.
     */
    virtual CATBoolean ActionOne(void *data);

private:
    CATPathElementAgent *_daPathElement;
    CATSoftwareConfiguration *pSoftConfig;
    CATTopData TopData;
};

//----------------------------------------------------------------------

#endif
