# COPYRIGHT Dassault Systemes 2025
#======================================================================
# Imakefile for module CAAPluginWks.m
#======================================================================
#
#  Jan 2025  Creation: Code generated by the CAA wizard  root
#======================================================================
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0FM JS0GROUP CATPrsWksPRDWorkshop ProductStructureUIUUID CATMechanicalModelerUI MechanicalModelerUIUUID
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) ApplicationFrame
#  CATMathematics CATDialogEngine

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
