// COPYRIGHT Dassault Systemes 2024
//===================================================================
//
// FunctionWks.cpp
// Provide implementation to interface
//    CATIPRDWorkshopAddin
//    CATIPrtWksAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Dec 2024  Creation: Code generated by the CAA wizard  root
//===================================================================
#include "FunctionWks.h"

#include <CATCommandHeader.h>
#include <CATCreateWorkshop.h>
MacDeclareHeader(FunctionHdr);
CATImplementClass(FunctionWks, Implementation, CATBaseUnknown, CATnull);

//-----------------------------------------------------------------------------
// FunctionWks : constructor
//-----------------------------------------------------------------------------
FunctionWks::FunctionWks()
    : CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// FunctionWks : destructor
//-----------------------------------------------------------------------------
FunctionWks::~FunctionWks()
{
}

// Link the implementation to its interface
// ---------------------------------------

void FunctionWks::CreateCommands()
{
    new FunctionHdr("Function1Hdr", "FunctionCommands", "Function1Cmd", (void *)0);
}

CATCmdContainer *FunctionWks::CreateToolbars()
{
    NewAccess(CATCmdContainer, pFunctionTlb, FunctionWks);

    NewAccess(CATCmdStarter, pCmdFunction1, Function1Str);
    SetAccessCommand(pCmdFunction1, "Function1Hdr");
    SetAccessChild(pFunctionTlb, pCmdFunction1);

    AddToolbarView(pFunctionTlb, 1, Left);
    return pFunctionTlb;
}

// TIE or TIEchain definitions
#include "TIE_CATIPRDWorkshopAddin.h"
TIE_CATIPRDWorkshopAddin(FunctionWks);
#include "TIE_CATIPrtWksAddin.h"
TIE_CATIPrtWksAddin(FunctionWks);

// Methods implementation
