// COPYRIGHT Dassault Systemes 2024
//===================================================================
//
// FunctionWks.h
// Provide implementation to interface
//    CATIPRDWorkshopAddin
//    CATIPrtWksAddin

//
//===================================================================
//
// Usage notes:
//
//===================================================================
// CAA2 Wizard Generation Report
// IMPLEMENTATION
//    TIE: CATIPRDWorkshopAddin
//    TIE: CATIPrtWksAddin

// End CAA2 Wizard Generation Report
//
//   Dec 2024  Creation: Code generated by the CAA wizard  root
//===================================================================
#ifndef FunctionWks_H
#define FunctionWks_H

#include "CATBaseUnknown.h"

class CATCmdContainer;

//-----------------------------------------------------------------------

/**
 * Class representing xxx.
 *
 * <br><b>Role</b>: Provide the basic class function...
 * <p>
 * It implements the interfaces :
 *  <ol>
 *  <li>@href CATIPRDWorkshopAddin
 *  <li>@href CATIPrtWksAddin
 *  </ol>
 *
 * @href ClassReference, Class#MethodReference, #InternalMethod...
 */
class FunctionWks: public CATBaseUnknown
{
    CATDeclareClass;

public:
    // Standard constructors and destructors for an implementation class
    // -----------------------------------------------------------------
    FunctionWks();
    virtual ~FunctionWks();

    void CreateCommands();
    CATCmdContainer *CreateToolbars();

private:
    // The copy constructor and the equal operator must not be implemented
    // -------------------------------------------------------------------
    FunctionWks(FunctionWks &);
    FunctionWks &operator=(FunctionWks &);
};

//-----------------------------------------------------------------------

#endif
