# COPYRIGHT Dassault Systemes 2025
#======================================================================
# Imakefile for module CAAPluginCmd.m
#======================================================================
#
#  Jan 2025  Creation: Code generated by the CAA wizard  root
#======================================================================
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0FM JS0GROUP CATPrsWksPRDWorkshop ProductStructureUIUUID CATMechanicalModelerUI MechanicalModelerUIUUID  \
DI0PANV2 CATMathematics CATDialogEngine
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) \
	CATGeometricObjects \
	CATGMModelInterfaces \
	CATGMOperatorsInterfaces \
	CATMathStream \
	CATMecModInterfaces \
	CATObjectSpecsModeler \
	CATViz

LOCAL_CCFLAGS = -EHsc -wd4819
SYS_LIBS = CAAPlugin.lib

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
