# COPYRIGHT Dassault Systemes 2024
#======================================================================
# Imakefile for module Function.m
#======================================================================
#
#  Dec 2024  Creation: Code generated by the CAA wizard  root
#======================================================================
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) \
	CATGeometricObjects \
	CATGitInterfaces \
	CATGMModelInterfaces \
	CATGMOperatorsInterfaces \
	CATInteractiveInterfaces \
	CATMathematics \
	CATMeasureGeometryInterfaces \
	CATMecModInterfaces \
	CATObjectModelerBase \
	CATObjectSpecsModeler \
	CATProductStructure1 \
	CATViz \
	KnowledgeItf

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
