// COPYRIGHT Dassault Systemes 2025
//===================================================================
//
// CAAPluginWks.h
// Provide implementation to interface
//    CATIPRDWorkshopAddin
//    CATIPrtWksAddin

//
//===================================================================
//
// Usage notes:
//
//===================================================================
// CAA2 Wizard Generation Report
// IMPLEMENTATION
//    TIE: CATIPRDWorkshopAddin
//    TIE: CATIPrtWksAddin

// End CAA2 Wizard Generation Report
//
//   Jan 2025  Creation: Code generated by the CAA wizard  root
//===================================================================
#ifndef CAAPluginWks_H
#define CAAPluginWks_H

#include "CATBaseUnknown.h"

class CATCmdContainer;

//-----------------------------------------------------------------------

/**
 * Class representing xxx.
 *
 * <br><b>Role</b>: Provide the basic class function...
 * <p>
 * It implements the interfaces :
 *  <ol>
 *  <li>@href CATIPRDWorkshopAddin
 *  <li>@href CATIPrtWksAddin
 *  </ol>
 *
 * @href ClassReference, Class#MethodReference, #InternalMethod...
 */
class CAAPluginWks: public CATBaseUnknown
{
    CATDeclareClass;

public:
    // Standard constructors and destructors for an implementation class
    // -----------------------------------------------------------------
    CAAPluginWks();
    virtual ~CAAPluginWks();

    void CreateCommands();
    CATCmdContainer *CreateToolbars();

private:
    // The copy constructor and the equal operator must not be implemented
    // -------------------------------------------------------------------
    CAAPluginWks(CAAPluginWks &);
    CAAPluginWks &operator=(CAAPluginWks &);
};

//-----------------------------------------------------------------------

#endif
