// COPYRIGHT Dassault Systemes 2025
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework FunctionFrm
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Dec 2024  Creation: Code generated by the CAA wizard  root
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System", Protected);
AddPrereqComponent("MechanicalModelerUI", Protected);
AddPrereqComponent("ProductStructureUI", Protected);
AddPrereqComponent("DialogEngine", Protected);
AddPrereqComponent("Mathematics", Protected);
AddPrereqComponent("Dialog", Protected);
// END WIZARD EDITION ZONE
AddPrereqComponent("Administration", Protected);
AddPrereqComponent("AdvancedMachiningInterfaces", Protected);
AddPrereqComponent("AdvancedMathematics", Protected);
AddPrereqComponent("AdvancedTopologicalOpe", Protected);
AddPrereqComponent("AdvancedTopologicalOpeLight", Protected);
AddPrereqComponent("AnalysisMeshingModel", Protected);
AddPrereqComponent("AnalysisMeshingToolsItf", Protected);
AddPrereqComponent("ApplicationFrame", Protected);
AddPrereqComponent("AutomationInterfaces", Protected);
AddPrereqComponent("BasicTopologicalOpe", Protected);
AddPrereqComponent("BatchInfrastructure", Protected);
AddPrereqComponent("BSFBuildtimeData", Protected);
AddPrereqComponent("CAACloudQsrItf", Protected);
AddPrereqComponent("CAACompositesItf", Protected);
AddPrereqComponent("CATAnalysisBase", Protected);
AddPrereqComponent("CATAnalysisGPSInterfaces", Protected);
AddPrereqComponent("CATAnalysisInterfaces", Protected);
AddPrereqComponent("CATAnalysisResources", Protected);
AddPrereqComponent("CATAnalysisVisuInterfaces", Protected);
AddPrereqComponent("CATArrangementInterfaces", Protected);
AddPrereqComponent("CATAssemblyInterfaces", Protected);
AddPrereqComponent("CATBehaviorInterfaces", Protected);
AddPrereqComponent("CATCloudEditorInterfaces", Protected);
AddPrereqComponent("CATCloudQsrInterfaces", Protected);
AddPrereqComponent("CATCommonLayoutInterfaces", Protected);
AddPrereqComponent("CATDataExchControlAlgo", Protected);
AddPrereqComponent("CATFunctSystemItf", Protected);
AddPrereqComponent("CATGraphicProperties", Protected);
AddPrereqComponent("CATGSMUseItf", Protected);
AddPrereqComponent("CATGSOUseItf", Protected);
AddPrereqComponent("CATHVDiagramInterfaces", Protected);
AddPrereqComponent("CATIAApplicationFrame", Protected);
AddPrereqComponent("CATIAV4Interfaces", Protected);
AddPrereqComponent("CATInstantCollabDesignCAAItf", Protected);
AddPrereqComponent("CATMatInterfaces", Protected);
AddPrereqComponent("CATMultiCADInterfaces", Protected);
AddPrereqComponent("CATOBMInterfaces", Protected);
AddPrereqComponent("CATPDMBase", Protected);
AddPrereqComponent("CATPDMBaseInterfaces", Protected);
AddPrereqComponent("CATPDMReconcile", Protected);
AddPrereqComponent("CATPIDiagramInterfaces", Protected);
AddPrereqComponent("CATPlantShipInterfaces", Protected);
AddPrereqComponent("CATPlantShipModeler", Protected);
AddPrereqComponent("CATPLMDictionary", Protected);
AddPrereqComponent("CATRdgInterfaces", Protected);
AddPrereqComponent("CATSchPlatformInterfaces", Protected);
AddPrereqComponent("CATSchPlatformModeler", Protected);
AddPrereqComponent("CATSdeSettingInterfaces", Protected);
AddPrereqComponent("CATSketcherUseItf", Protected);
AddPrereqComponent("CATSmaInterfaces", Protected);
AddPrereqComponent("CATSmInterfaces", Protected);
AddPrereqComponent("CATSurfacicOpeInterfaces", Protected);
AddPrereqComponent("CATTBDiagramInterfaces", Protected);
AddPrereqComponent("CATTPSInterfaces", Protected);
AddPrereqComponent("CATTPSUIResources", Protected);
AddPrereqComponent("CATTTRSInterfaces", Protected);
AddPrereqComponent("CATTubingInterfaces", Protected);
AddPrereqComponent("CATWGDiagramInterfaces", Protected);
AddPrereqComponent("CATxPDMInterfaces", Protected);
AddPrereqComponent("CDMAInteroperability", Protected);
AddPrereqComponent("Communications", Protected);
AddPrereqComponent("ComponentsCatalogsInterfaces", Protected);
AddPrereqComponent("ConstraintModeler", Protected);
AddPrereqComponent("ConstraintModelerInterfaces", Protected);
AddPrereqComponent("CORBAServerInfra", Protected);
// AddPrereqComponent("DialogEngine", Protected);
// AddPrereqComponent("Dialog", Protected);
AddPrereqComponent("DMAPSInterfaces", Protected);
AddPrereqComponent("Drafting2DLInterfaces", Protected);
AddPrereqComponent("DraftingInterfaces", Protected);
AddPrereqComponent("ElecDeviceItf", Protected);
AddPrereqComponent("ElecFlatteningItf", Protected);
AddPrereqComponent("ElecHarnessItf", Protected);
AddPrereqComponent("ElecRoutingItf", Protected);
AddPrereqComponent("ElecSchematicItf", Protected);
AddPrereqComponent("ElectricalInterfaces", Protected);
AddPrereqComponent("ENOVaultClientCPP", Protected);
AddPrereqComponent("ENOVIAPlugIn", Protected);
AddPrereqComponent("FittingInterfaces", Protected);
AddPrereqComponent("FreeFormOperators", Protected);
AddPrereqComponent("GeometricObjects", Protected);
AddPrereqComponent("GeometricOperators", Protected);
AddPrereqComponent("GMModelInterfaces", Protected);
AddPrereqComponent("GMOperatorsInterfaces", Protected);
AddPrereqComponent("GSMInterfaces", Protected);
AddPrereqComponent("GSOInterfaces", Protected);
AddPrereqComponent("InteractiveInterfaces", Protected);
AddPrereqComponent("KinematicsInterfaces", Protected);
AddPrereqComponent("KnowHow", Protected);
AddPrereqComponent("KnowledgeInterfaces", Protected);
AddPrereqComponent("LatheMachiningInterfaces", Protected);
AddPrereqComponent("ManufacturingInterfaces", Protected);
AddPrereqComponent("Material", Protected);
// AddPrereqComponent("Mathematics", Protected);
AddPrereqComponent("MeasureGeometryInterfaces", Protected);
AddPrereqComponent("MechanicalCommands", Protected);
AddPrereqComponent("MechanicalModeler", Protected);
// AddPrereqComponent("MechanicalModelerUI", Protected);
AddPrereqComponent("MecModInterfaces", Protected);
AddPrereqComponent("NavigatorInterfaces", Protected);
AddPrereqComponent("NewTopologicalObjects", Protected);
AddPrereqComponent("ObjectModelerBase", Protected);
AddPrereqComponent("ObjectModelerNavigator", Protected);
AddPrereqComponent("ObjectModelerSDM", Protected);
AddPrereqComponent("ObjectModelerSystem", Protected);
AddPrereqComponent("ObjectSpecsModeler", Protected);
AddPrereqComponent("OptimizationInterfaces", Protected);
AddPrereqComponent("PartInterfaces", Protected);
AddPrereqComponent("PLMSecuritySSOBase", Protected);
AddPrereqComponent("PLMSecuritySSOCClient", Protected);
AddPrereqComponent("PrintBase", Protected);
AddPrereqComponent("Print", Protected);
AddPrereqComponent("PrismaticMachiningInterfaces", Protected);
AddPrereqComponent("ProcessPlatformVisu", Protected);
AddPrereqComponent("ProductStructure", Protected);
AddPrereqComponent("ProductStructureInterfaces", Protected);
// AddPrereqComponent("ProductStructureUI", Protected);
AddPrereqComponent("PSNInteroperability", Protected);
AddPrereqComponent("SDMRuntime", Protected);
AddPrereqComponent("SimulationBaseLegacy", Protected);
AddPrereqComponent("SimulationInterfaces", Protected);
AddPrereqComponent("SketcherInterfaces", Protected);
AddPrereqComponent("SketcherToolsUI", Protected);
AddPrereqComponent("SketcherUI", Protected);
AddPrereqComponent("SpaceAnalysisInterfaces", Protected);
AddPrereqComponent("SpecialAPI", Protected);
AddPrereqComponent("StructureInterfaces", Protected);
AddPrereqComponent("SurfaceMachiningInterfaces", Protected);
// AddPrereqComponent("System", Protected);
AddPrereqComponent("Tessellation", Protected);
AddPrereqComponent("ToolPathEditorInterfaces", Protected);
AddPrereqComponent("TopologicalOperators", Protected);
AddPrereqComponent("TopologicalOperatorsLight", Protected);
AddPrereqComponent("V5ToV4Geo", Protected);
AddPrereqComponent("VisualizationBase", Protected);
AddPrereqComponent("Visualization", Protected);
AddPrereqComponent("VPMInterfaces", Protected);
AddPrereqComponent("VPMServices", Protected);
AddPrereqComponent("XMLParser", Protected);
