// COPYRIGHT Dassault Systemes 2024
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework FunctionFrm
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Dec 2024  Creation: Code generated by the CAA wizard  root
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System", Protected);
AddPrereqComponent("MechanicalModelerUI", Protected);
AddPrereqComponent("ProductStructureUI", Protected);
AddPrereqComponent("DialogEngine", Protected);
AddPrereqComponent("Mathematics", Protected);
AddPrereqComponent("Dialog", Protected);
// END WIZARD EDITION ZONE
AddPrereqComponent("ApplicationFrame", Public);
