// COPYRIGHT Dassault Systemes 2024
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework FunctionFrm
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Dec 2024  Creation: Code generated by the CAA wizard  root
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System", Protected);
AddPrereqComponent("MechanicalModelerUI", Protected);
AddPrereqComponent("ProductStructureUI", Protected);
AddPrereqComponent("DialogEngine", Protected);
AddPrereqComponent("Mathematics", Protected);
AddPrereqComponent("Dialog", Protected);
// END WIZARD EDITION ZONE
AddPrereqComponent("Administration", Public);
AddPrereqComponent("AdvancedMachiningInterfaces", Public);
AddPrereqComponent("AdvancedMathematics", Public);
AddPrereqComponent("AdvancedTopologicalOpe", Public);
AddPrereqComponent("AdvancedTopologicalOpeLight", Public);
AddPrereqComponent("AnalysisMeshingModel", Public);
AddPrereqComponent("AnalysisMeshingToolsItf", Public);
AddPrereqComponent("ApplicationFrame", Public);
AddPrereqComponent("AutomationInterfaces", Public);
AddPrereqComponent("BasicTopologicalOpe", Public);
AddPrereqComponent("BatchInfrastructure", Public);
AddPrereqComponent("BSFBuildtimeData", Public);
AddPrereqComponent("CAACloudQsrItf", Public);
AddPrereqComponent("CAACompositesItf", Public);
AddPrereqComponent("CATAnalysisBase", Public);
AddPrereqComponent("CATAnalysisGPSInterfaces", Public);
AddPrereqComponent("CATAnalysisInterfaces", Public);
AddPrereqComponent("CATAnalysisResources", Public);
AddPrereqComponent("CATAnalysisVisuInterfaces", Public);
AddPrereqComponent("CATArrangementInterfaces", Public);
AddPrereqComponent("CATAssemblyInterfaces", Public);
AddPrereqComponent("CATBehaviorInterfaces", Public);
AddPrereqComponent("CATCloudEditorInterfaces", Public);
AddPrereqComponent("CATCloudQsrInterfaces", Public);
AddPrereqComponent("CATCommonLayoutInterfaces", Public);
AddPrereqComponent("CATDataExchControlAlgo", Public);
AddPrereqComponent("CATFunctSystemItf", Public);
AddPrereqComponent("CATGraphicProperties", Public);
AddPrereqComponent("CATGSMUseItf", Public);
AddPrereqComponent("CATGSOUseItf", Public);
AddPrereqComponent("CATHVDiagramInterfaces", Public);
AddPrereqComponent("CATIAApplicationFrame", Public);
AddPrereqComponent("CATIAV4Interfaces", Public);
AddPrereqComponent("CATInstantCollabDesignCAAItf", Public);
AddPrereqComponent("CATMatInterfaces", Public);
AddPrereqComponent("CATMultiCADInterfaces", Public);
AddPrereqComponent("CATOBMInterfaces", Public);
AddPrereqComponent("CATPDMBase", Public);
AddPrereqComponent("CATPDMBaseInterfaces", Public);
AddPrereqComponent("CATPDMReconcile", Public);
AddPrereqComponent("CATPIDiagramInterfaces", Public);
AddPrereqComponent("CATPlantShipInterfaces", Public);
AddPrereqComponent("CATPlantShipModeler", Public);
AddPrereqComponent("CATPLMDictionary", Public);
AddPrereqComponent("CATRdgInterfaces", Public);
AddPrereqComponent("CATSchPlatformInterfaces", Public);
AddPrereqComponent("CATSchPlatformModeler", Public);
AddPrereqComponent("CATSdeSettingInterfaces", Public);
AddPrereqComponent("CATSketcherUseItf", Public);
AddPrereqComponent("CATSmaInterfaces", Public);
AddPrereqComponent("CATSmInterfaces", Public);
AddPrereqComponent("CATSurfacicOpeInterfaces", Public);
AddPrereqComponent("CATTBDiagramInterfaces", Public);
AddPrereqComponent("CATTPSInterfaces", Public);
AddPrereqComponent("CATTPSUIResources", Public);
AddPrereqComponent("CATTTRSInterfaces", Public);
AddPrereqComponent("CATTubingInterfaces", Public);
AddPrereqComponent("CATWGDiagramInterfaces", Public);
AddPrereqComponent("CATxPDMInterfaces", Public);
AddPrereqComponent("CDMAInteroperability", Public);
AddPrereqComponent("Communications", Public);
AddPrereqComponent("ComponentsCatalogsInterfaces", Public);
AddPrereqComponent("ConstraintModeler", Public);
AddPrereqComponent("ConstraintModelerInterfaces", Public);
AddPrereqComponent("CORBAServerInfra", Public);
AddPrereqComponent("DialogEngine", Public);
AddPrereqComponent("Dialog", Public);
AddPrereqComponent("DMAPSInterfaces", Public);
AddPrereqComponent("Drafting2DLInterfaces", Public);
AddPrereqComponent("DraftingInterfaces", Public);
AddPrereqComponent("ElecDeviceItf", Public);
AddPrereqComponent("ElecFlatteningItf", Public);
AddPrereqComponent("ElecHarnessItf", Public);
AddPrereqComponent("ElecRoutingItf", Public);
AddPrereqComponent("ElecSchematicItf", Public);
AddPrereqComponent("ElectricalInterfaces", Public);
AddPrereqComponent("ENOVaultClientCPP", Public);
AddPrereqComponent("ENOVIAPlugIn", Public);
AddPrereqComponent("FittingInterfaces", Public);
AddPrereqComponent("FreeFormOperators", Public);
AddPrereqComponent("GeometricObjects", Public);
AddPrereqComponent("GeometricOperators", Public);
AddPrereqComponent("GMModelInterfaces", Public);
AddPrereqComponent("GMOperatorsInterfaces", Public);
AddPrereqComponent("GSMInterfaces", Public);
AddPrereqComponent("GSOInterfaces", Public);
AddPrereqComponent("InteractiveInterfaces", Public);
AddPrereqComponent("KinematicsInterfaces", Public);
AddPrereqComponent("KnowHow", Public);
AddPrereqComponent("KnowledgeInterfaces", Public);
AddPrereqComponent("LatheMachiningInterfaces", Public);
AddPrereqComponent("ManufacturingInterfaces", Public);
AddPrereqComponent("Material", Public);
AddPrereqComponent("Mathematics", Public);
AddPrereqComponent("MeasureGeometryInterfaces", Public);
AddPrereqComponent("MechanicalCommands", Public);
AddPrereqComponent("MechanicalModeler", Public);
AddPrereqComponent("MechanicalModelerUI", Public);
AddPrereqComponent("MecModInterfaces", Public);
AddPrereqComponent("NavigatorInterfaces", Public);
AddPrereqComponent("NewTopologicalObjects", Public);
AddPrereqComponent("ObjectModelerBase", Public);
AddPrereqComponent("ObjectModelerNavigator", Public);
AddPrereqComponent("ObjectModelerSDM", Public);
AddPrereqComponent("ObjectModelerSystem", Public);
AddPrereqComponent("ObjectSpecsModeler", Public);
AddPrereqComponent("OptimizationInterfaces", Public);
AddPrereqComponent("PartInterfaces", Public);
AddPrereqComponent("PLMSecuritySSOBase", Public);
AddPrereqComponent("PLMSecuritySSOCClient", Public);
AddPrereqComponent("PrintBase", Public);
AddPrereqComponent("Print", Public);
AddPrereqComponent("PrismaticMachiningInterfaces", Public);
AddPrereqComponent("ProcessPlatformVisu", Public);
AddPrereqComponent("ProductStructure", Public);
AddPrereqComponent("ProductStructureInterfaces", Public);
AddPrereqComponent("ProductStructureUI", Public);
AddPrereqComponent("PSNInteroperability", Public);
AddPrereqComponent("SDMRuntime", Public);
AddPrereqComponent("SimulationBaseLegacy", Public);
AddPrereqComponent("SimulationInterfaces", Public);
AddPrereqComponent("SketcherInterfaces", Public);
AddPrereqComponent("SketcherToolsUI", Public);
AddPrereqComponent("SketcherUI", Public);
AddPrereqComponent("SpaceAnalysisInterfaces", Public);
AddPrereqComponent("SpecialAPI", Public);
AddPrereqComponent("StructureInterfaces", Public);
AddPrereqComponent("SurfaceMachiningInterfaces", Public);
AddPrereqComponent("System", Public);
AddPrereqComponent("Tessellation", Public);
AddPrereqComponent("ToolPathEditorInterfaces", Public);
AddPrereqComponent("TopologicalOperators", Public);
AddPrereqComponent("TopologicalOperatorsLight", Public);
AddPrereqComponent("V5ToV4Geo", Public);
AddPrereqComponent("VisualizationBase", Public);
AddPrereqComponent("Visualization", Public);
AddPrereqComponent("VPMInterfaces", Public);
AddPrereqComponent("VPMServices", Public);
AddPrereqComponent("XMLParser", Public);
